name: precily_pipeline

on:
  push:
    branches: [ "main" ]

env:
 CI: false


jobs:
  docker:
    name: Docker 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: flask_ocr
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ashishizofficial/api-flask:tess-${{ github.sha }}
          file: ./Dockerfile
          context: .


 

  deploy-staging:
    needs: ["docker"]
    if: github.ref == 'refs/heads/main'
    name: Deploy-Production
    runs-on: [self-hosted, precily]
    steps:
    - run: 
         /home/ec2-user/script.sh